CREATE TABLE historical (
  id UUID PRIMARY KEY NOT NULL,
  code VARCHAR(3) NOT NULL,
  brand VARCHAR NOT NULL,
  indexreturn DOUBLE PRECISION NOT NULL,
  nav DOUBLE PRECISION NOT NULL,
  asofdate TIMESTAMP NOT NULL,
  exdividend DOUBLE PRECISION NOT NULL,
  createdat TIMESTAMP NOT NULL
)